services:
  app:
    build: .
    command: flask run -h app
    ports:
      - 127.0.0.1:5000:5000/tcp
    volumes:
      - ./:/usr/src/app
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db
      SECRET_KEY: a_very_secret_key

  db:
    image: postgres:17-alpine
    volumes:
      - ./database:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
