services:
  app:
    image: tsoha
    build: .
    command: flask run -h app
    ports:
      - 127.0.0.1:5000:5000/tcp
    volumes:
      - ./:/app
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db
      SECRET_KEY: a_very_secret_key
    stop_signal: SIGKILL
    depends_on:
      - db

  db:
    image: postgres:17-alpine
    volumes:
      - db:/var/lib/postgresql/data
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql:ro
      - ./testdata.sql:/docker-entrypoint-initdb.d/testdata.sql:ro
    environment:
      POSTGRES_PASSWORD: postgres

volumes:
  db:
