CREATE TABLE users (
    id SERIAL PRIMARY KEY,
    username TEXT UNIQUE,
    password TEXT,
    admin BOOLEAN DEFAULT FALSE
);
CREATE TABLE subforums (
    id SERIAL PRIMARY KEY,
    title TEXT UNIQUE,
    description TEXT
);
CREATE TABLE threads (
    id SERIAL PRIMARY KEY,
    uid INTEGER,
    subforum INTEGER,
    title TEXT,
    first_msg INTEGER
);
CREATE TABLE messages (
    id SERIAL PRIMARY KEY,
    uid INTEGER,
    thread INTEGER,
    content TEXT,
    sent TIMESTAMP DEFAULT NOW()
);
CREATE TABLE message_tree_paths (
    ancestor INTEGER,
    descendant INTEGER,
    depth INTEGER CHECK (depth >= 0),
    UNIQUE (ancestor, descendant)
);
CREATE TABLE likes (
    uid INTEGER,
    message INTEGER,
    value INTEGER CHECK (value = 1 OR value = -1),
    UNIQUE (uid, message)
);

ALTER TABLE threads ADD FOREIGN KEY (uid) REFERENCES users ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE threads ADD FOREIGN KEY (subforum) REFERENCES subforums ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE threads ADD FOREIGN KEY (first_msg) REFERENCES messages ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE messages ADD FOREIGN KEY (uid) REFERENCES users ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE messages ADD FOREIGN KEY (thread) REFERENCES threads ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE message_tree_paths ADD FOREIGN KEY (ancestor) REFERENCES messages ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE message_tree_paths ADD FOREIGN KEY (descendant) REFERENCES messages ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE likes ADD FOREIGN KEY (uid) REFERENCES users ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE likes ADD FOREIGN KEY (message) REFERENCES messages ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED;
