INSERT INTO messages (content) VALUES ('Terve, maailma!');
INSERT INTO messages (content) VALUES ('Jotain muuta...');
INSERT INTO messages (content) VALUES ('Mitä muuta?');
INSERT INTO messages (content) VALUES ('Vielä yksi viesti.');
INSERT INTO message_tree_paths (ancestor, descendant, depth) VALUES (1, 1, 0);
INSERT INTO message_tree_paths (ancestor, descendant, depth) VALUES (1, 2, 1);
INSERT INTO message_tree_paths (ancestor, descendant, depth) VALUES (1, 3, 2);
INSERT INTO message_tree_paths (ancestor, descendant, depth) VALUES (1, 4, 1);
INSERT INTO message_tree_paths (ancestor, descendant, depth) VALUES (2, 2, 0);
INSERT INTO message_tree_paths (ancestor, descendant, depth) VALUES (2, 3, 1);
INSERT INTO message_tree_paths (ancestor, descendant, depth) VALUES (3, 3, 0);
INSERT INTO message_tree_paths (ancestor, descendant, depth) VALUES (4, 4, 0);
